[tool.poetry]
name = "nzshm-model"
version = "0.2.0"
description = "The logic tree definitions, final configurations, and versioning of the New Zealand | Aotearoa National Seismic Hazard Model"
authors = ["Chris DiCaprio <c.dicaprio@gns.cri.nz>", "Chris Chamberlain <chrisbc@artisan.co.nz>"]
license = "AGPL3"
readme = "README.md"
packages = [
	{include = "nzshm_model"},
	{include = "scripts"},
    {include = "tests", format = "sdist" }
]

[tool.poetry.scripts]
slt = 'scripts.slt:slt'

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
nshm-toshi-client = {version = ">=1.0.0", extras = ["toshi"], optional = true}
boto3 = {extras = ["toshi"], version = "^1.26.28", optional = true}
click = {extras = ["scripts"], version = "^8.1.3", optional = true}
dacite = "^1.6.0"

[tool.poetry.extras]
test = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "flake8",
    "flake8-docstrings",
    "pytest-cov"
    ]
toshi = [
    "boto3",
    "nshm-toshi-client"
    ]
scripts = [
    "click"
]

dev = ["tox", "pre-commit", "virtualenv", "pip", "twine", "toml", "bump2version"]

[tool.poetry.group.dev.dependencies]
black  = { version = "^22.3"}
bump2version = "^1.0.1"
isort  = { version = "^5.8.0"}
flake8  = { version = "^3.9.2"}
flake8-docstrings = { version = "^1.6.0", optional = true }
mypy = {version = "^0.900"}
pytest = { version = "^6.2.4"}
pytest-cov  = { version = "^2.12.0"}
tox = "^4.2.8"

twine = "^4.0.2"

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py310', 'py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = true
# you can skip files as below
#skip_glob = docs/conf.py

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
