name: Run Tests 

#https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

on:
  workflow_call:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-versions: [3.9]
        os: [ubuntu-latest]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies w Poetry
        run: |
          poetry install --with dev
          poetry add tox-gh-actions

      - name: test with tox (uses tox-gh-actions to select correct environment)
        run:
          poetry run tox

      - name: list files
        run: ls -l .

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          files: coverage.xml
