name: Run Tests 

#https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

on:
  workflow_call:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: [3.9, '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: GNS-Science/install-poetry@main
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies w Poetry
        run: |
          poetry install --all-extras
          poetry add tox-gh-actions

      - name: test with tox (uses tox-gh-actions to select correct environment)
        run:
          poetry run tox

      - name: list files
        run: ls -l .

      - name: Submit coverage report if Ubuntu and we're on 'main' branch
        if: runner.os == 'Linux' && runner.python-version == '3.11'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
          # fail_ci_if_error: true # optional (default = false)